### ISSUE TITLE
Stylen der Reservierungen, Hinzufügen von Logik zum löschen und ausleihen, wenn wieder verfügbar

### ISSUE THREAD

**Issue by Heyjoo3** [saltyniggo/BAMBUS#52]
- [x] Reservierungen in Base Container Narrow
- [x] Button zum Auleihen, erst aktiv wenn verfügbar
- [x] Button zum Löschen

**Comment by saltyniggo** [comment]
überall gehen funktionen von uns, alles fackelt ab, aber die button funktionieren oida
